apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: "<h1>Welcome to nginx</h1>"
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }

# kubectl apply -f configmap.yaml
# kubectl get cm
# kubectl create configmap nginx-config --from-file=index.html --from-file=nginx.conf
# kubectl create configmap nginx-config --from-literal=key1=value1 --from-literal=key2=value2 


