apiVersion: v1
kind: Config
current-context: mdak@development

clusters:
  - name: development
    cluster:
      certificate-authority: /etc/kubernetes/pki/ca.crt
      server: https://192.168.23.1:
  - name: production
    cluster:
      certificate-authority: /etc/kubernetes/pki/ca.crt
      server: https://
  - name: local
    cluster:
      certificate-authority: /etc/kubernetes/pki/ca.crt
      server: https://

users:
  - name: hxri
    user:
      client-certificate: /etc/kubernetes/pki/users/hxri.crt
      client-key: /etc/kubernetes/pki/users/hxri.key
  - name: mdak
    user:
      client-certificate: /etc/kubernetes/pki/users/mdak.crt
      client-key: /etc/kubernetes/pki/users/mdak.key
  - name: local-user
    user:
      client-certificate: /etc/kubernetes/pki/users/local-user.crt
      client-key: /etc/kubernetes/pki/users/local-user.key

contexts:
  - name: mdak@development
    context:
      cluster: development
      user: mdak
      namespace: redis
  - name: hxri@development
    context:
      cluster: development
      user: hxri
  - name: mdak@production 
    context:
      cluster: production
      user: mdak
