apiVersion: v1
kind: Config
current-context: mdak@development
clusters:
- name: development
  cluster:
    certificate-authority: /etc/kubernetes/pki/ca.crt
    server: https://172.13.0.5:6443
- name: production
  cluster:
    certificate-authority: /etc/kubernetes/pki/ca.crt
    server: https://172.13.0.6:6443
- name: local
  cluster:
    certificate-authority: /etc/kubernetes/pki/ca.crt
    server: https://172.31.0.7:6443
contexts:
- name: mdak@development
  context:
    cluster: development
    user: mdak
    namespace: redis
- name: hxri@development
  context:
    cluster: development
    user: hxri
- name: mdak@production
  context:
    cluster: production
    user: mdak
- name: local@local
  context:
    cluster: local
    user: local-user
users:
- name: hxri
  user:
    client-certificate: /etc/kubernetes/pki/users/hxri.crt
    client-key: /etc/kubernetes/pki/users/hxri.key
- name: mdak
  user:
    client-certificate: /etc/kubernetes/pki/users/mdak.crt
    client-key: /etc/kubernetes/pki/users/mdak.key
- name: local-user
  user:
    client-certificate: /etc/kubernetes/pki/users/local-user.crt
    client-key: /etc/kubernetes/pki/users/local-user.key


# to set the config file
# k config current-context --kubeconfig=kubeConfig.yaml


# u dont need to create this file, it will be created by kubectl
# kubectl config set-context --current --namespace=dev
# u can put this in kubeConfig.yaml file 

# export KUBECONFIG=/root/my-kube-config //so u dont have to specify in each command