apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
    - default:
        memory: 512Mi
      defaultRequest:
        memory: 256Mi
      min:
        memory: 128Mi
      max:
        memory: 2Gi
      type: Container

# kubectl get limitrange
# kubectl describe limitrange mem-limit-range
# kubectl delete limitrange mem-limit-range
# kubectl get limitrange
