apiVersion: v1
kind: Binding
metadata:
  name: nginx-binding 
target:
  apiVersion: v1
  kind: Node
  name: minikube

# curl -X POST -H "Content-Type: application/json" --data @pod-bind.json http://$SERVER/api/v1/namespaces/default/pods/nginx/binding/