apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
globalDefault: false


# now in pod u can use this priority class as spec.priorityClassName: high-priority


