apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 5Gi
    limits.cpu: "10"
    limits.memory: 10Gi
    persistentvolumeclaims: "4"
    services: "5"
    services.loadbalancers: "2"
    services.nodeports: "2"
    configmaps: "10"
    secrets: "10"
 
#  kubectl get resourcequota
# kubectl describe resourcequota compute-quota
# kubectl delete resourcequota compute-quota
# this is resourceqouta applies accross the namespace