apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username : base64encodedusername
  password : base64encodedpassword
  email : YmFzZTY0ZW5jb2RlZGVtYWls

# kubectl apply -f secret.yaml
# kubectl get secret //u cant see the data
# kubectl get secret mysecret -o yaml
# kubectl create secret generic mysecret --from-literal=username=dev
