apiVersion: v1
kind: StorageClass
metadata:
  name: gce-standard
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: none

---
 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: MYAPP-pvc
  namespace: default
  labels:
    app: MYAPP-pvc
spec:
  storageClassName: gce-standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi