apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-scheduler-binding
roleRef: # role details
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-scheduler-role
subjects: # user details / service account
- kind: ServiceAccount
  name: custom-scheduler-sa
  namespace: kube-system
