apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  renewDeadline: 10s
  retryPeriod: 2s
profiles:
  - schedulerName: my-scheduler
  plugins:
      prefilter:
        enabled:
          - "MyCustomFilterPlugin"  
    pluginConfig:
      - name: "MyCustomFilterPlugin"
        args: {}

# k create configmap my-scheduler-config --from-file=my-scheduler-config.yaml -n kube-system
# k edit deployment kube-scheduler -n kube-system
