apiVersion: v1
kind: Pod
metadata:
  name: custom-scheduler-pod
  namespace: kube-system
spec:
  serviceAccountName: custom-scheduler-sa
  containers:
  - name: custom-scheduler
    image: k8s.gcr.io/kube-scheduler:v1.20.0
    command:
    - /usr/local/bin/kube-scheduler
    - --config=/etc/kubernetes/config/scheduler-config.yaml
    volumeMounts:
    - name: config-volume
      mountPath: /etc/kubernetes/config
  volumes:
  - name: config-volume
    configMap:
      name: custom-scheduler-config
