apiVersion: rbac.authorization.k8s.io
kind: ClusterRole
metadata:
  name: cluster-dev-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]





# here also u can specify pods or deployments or configmaps but then it will be accros all namespaces